"""remove unique username

Revision ID: 7b799f1567c8
Revises: 046d4e456879
Create Date: 2026-07-26 12:36:37.898300

"""


from alembic import op

# revision identifiers, used by Alembic.
revision = "7b799f1567c8"
down_revision = "046d4e456879"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_auth_user_username"), table_name="auth_user")
    op.create_index(
        op.f("ix_auth_user_username"), "auth_user", ["username"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_auth_user_username"), table_name="auth_user")
    op.create_index(
        op.f("ix_auth_user_username"), "auth_user", ["username"], unique=True
    )
    # ### end Alembic commands ###
