"""add username to auth_user

Revision ID: 046d4e456879
Revises: 683275eeb305
Create Date: 2026-07-14 10:54:41.894454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046d4e456879'
down_revision = '683275eeb305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('username', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_auth_user_username'), 'auth_user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_user_username'), table_name='auth_user')
    op.drop_column('auth_user', 'username')
    # ### end Alembic commands ###
